version: "3"

services:
  jenkins:
    container_name: jenkins
    image: metfan1981/jenkins:latest
    ports: 
      - "8080:8080"
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - custom-net

networks:
  custom-net:

volumes:
  jenkins:
